#!/bin/bash

set -m

while :; do
    (cd /home/bczhc/code/vibecoded/softbuffer-big-text; ./wl-paper-show 'Morse' -f /usr/share/fonts/noto/NotoSerif-Bold.ttf -s 400 -c ff0000 -x $((2560/2)) -y 300 --no-blink) &
    child_pid=$!

    while :; do
        if [ -f /tmp/morse-dismiss ]; then
            rm /tmp/morse-dismiss
            kill -TERM -$child_pid
            break
        fi
        sleep 1
    done

    sleep 7200 # 2h
done
