#!/bin/bash

set -e

basedir="$(dirname "$(realpath "$0")")"

rsync -a --delete ~/bin/scripts ~/bin/rofi ~/bin/polybar-scripts bin/
rm -rf bin/rofi/rofi-iwd-wifi-menu
cp ~/.ssh/config .ssh/

cd ~
cp .vimrc .xinitrc .zshrc .Xmodmap .p10k.zsh .gitconfig "$basedir"

cd ~/.config
rsync -a --delete i3 polybar rofi mpv alacritty picom dunst neofetch htop yazi tmux-powerline \
  "$basedir/.config/"

cd "$basedir"

# tmux
rsync -a ~/.config/./tmux/tmux.conf .config --delete --relative
