#!/bin/bash

set -e

basedir="$(dirname "$(realpath "$0")")"

rsync -a --delete ~/bin/scripts ~/bin/rofi ~/bin/polybar-scripts bin/
rm -rf bin/rofi/rofi-iwd-wifi-menu
cp ~/.ssh/config .ssh/

cd ~
cp .vimrc .xinitrc .zshrc .Xmodmap .p10k.zsh .gitconfig "$basedir"

cd ~/.config
rsync -a --delete i3 polybar rofi mpv alacritty picom dunst neofetch ranger htop \
  "$basedir/.config/"

cd "$basedir"
mkdir Screenrecords 2>/dev/null || true
fd . -t x ~/Screenrecords -j1 -x cp -v {} Screenrecords/
