#unbind C-b
#set-option -g prefix C-s
#bind-key C-s send-prefix

# For displaying Sixel
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set-option -g set-titles on
set-option -g set-titles-string "tmux - #{pane_title}"
set-option -g allow-rename on
set-option -g allow-set-title on
set-window-option -g automatic-rename on

#set -g extended-keys on
#set -g default-terminal "tmux-256color"

#set-window-option -g xterm-keys on
#set -g xterm-keys on
#set -g default-terminal "xterm-256color"

# == Plugins ==
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
