#!/bin/bash

abspath="$(readlink -f "$0")"
absdir="$(dirname "$abspath")"
home_folder="$absdir"/home

exec bwrap \
  --unshare-user \
  --unshare-ipc \
  --unshare-pid \
  --unshare-uts \
  --ro-bind /usr /usr \
  --ro-bind /lib /lib \
  --ro-bind-try /lib64 /lib64 \
  --ro-bind /bin /bin \
  --ro-bind /etc /etc \
  --dev /dev \
  --proc /proc \
  --tmpfs /tmp \
  --tmpfs /run \
  --dir /home \
  --bind "$home_folder" "$HOME" \
  --ro-bind /home/bczhc/bin/sqfs/NCM-Open-Orpheus /opt/app \
  --ro-bind-try ~/.config/fontconfig "$HOME"/.config/fontconfig \
  --bind-try ~/.cache/fontconfig "$HOME"/.cache/fontconfig \
  --ro-bind-try ~/.Xauthority "$HOME"/.Xauthority \
  --bind-try /run/user/1000/wayland-1 /run/user/1000/wayland-1 \
  --ro-bind-try /tmp/.X11-unix/X0 /tmp/.X11-unix/X0 \
  --ro-bind-try /etc/resolv.conf /etc/resolv.conf \
  --ro-bind-try /run/user/1000/bus /run/user/1000/bus \
  --dev-bind-try /dev/snd /dev/snd \
  --ro-bind-try /run/user/1000/pulse /run/user/1000/pulse \
  --setenv DISPLAY "$DISPLAY" \
  --setenv XAUTHORITY "$HOME"/.Xauthority \
  --unsetenv http_proxy --unsetenv https_proxy \
  --tmpfs "$HOME"/.config/open-orpheus/cache/play \
  --dev-bind-try /dev/dri /dev/dri \
  --ro-bind-try /usr/lib/dri /usr/lib/dri \
  --ro-bind-try /usr/lib64/dri /usr/lib64/dri \
  --ro-bind-try /usr/share/drirc.d /usr/share/drirc.d \
  --ro-bind-try /usr/lib/xorg/modules/drivers /usr/lib/xorg/modules/drivers \
  /opt/app/AppRun --disable-gpu --disable-software-rasterizer


  #bash -c 'open-orpheus'
