[colors.primary]
background = '#fefefe'
foreground = '#1c1b1f'

[colors.selection]
text = '#1c1b1f'
background = '#fce4ec'

[colors.cursor]
text = '#fefefe'
cursor = '#cc4d82'

[colors.normal]
black   = '#1C1B1F'
red     = '#c13138'
green   = '#3d991d'
yellow  = '#f4c410'
blue    = '#d64a84'
magenta = '#ffcce1'
cyan    = '#CC4D82'
white   = '#393637'

[colors.bright]
black   = '#ada8aa'
red     = '#f45c64'
green   = '#6ee046'
yellow  = '#ffd020'
blue    = '#ea498c'
magenta = '#ffcce1'
cyan    = '#ffafd0'
white   = '#fff8fb'
