[colors.primary]
background = '#faf8ff'
foreground = '#191b23'

[colors.selection]
text = '#191b23'
background = '#77a15d'

[colors.cursor]
text = '#faf8ff'
cursor = '#2f5419'

[colors.normal]
black   = '#11131a'
red     = '#792613'
green   = '#0d5f08'
yellow  = '#998500'
blue    = '#2f5817'
magenta = '#7f9473'
cyan    = '#2f5419'
white   = '#222321'

[colors.bright]
black   = '#696c68'
red     = '#af553e'
green   = '#258c1f'
yellow  = '#a59002'
blue    = '#4c7b2f'
magenta = '#7f9473'
cyan    = '#556d46'
white   = '#bbbfb9'
