#!/bin/bash

if [ $# != 3 ]; then
    echo 'Usage: command <input> <output> <crf>'
    exit 1
fi

ffmpeg -i "$1" -c:a libopus -b:a 96k -c:v libaom-av1 -crf "$3" -threads 16 -cpu-used 5 -tile-rows 2 -tile-columns 2 -row-mt 1 -tune 0 -pix_fmt yuv420p "$2"
