#!/bin/bash

set -e

if screen -list | grep screenrecord; then
    ./screen-stop
    notify-send stop -t 2000
    # ensure the session is terminated
    sleep 5
    screen -S screenrecord -X quit || true
else
    ./screen-start
    notify-send start -t 500
fi
