#!/bin/bash

dir="$(dirname "$0")"
proton_dir="$(readlink -f "$dir"/proton)"
pdd="$(readlink -f "$dir"/proton-data)"

cd "$dir"/Minecraft\ for\ Windows/Content

MANGOHUD=1 PROTON_ENABLE_HDR=0 PROTON_ENABLE_WAYLAND=1 STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME"/.steam/steam STEAM_COMPAT_DATA_PATH="$pdd" "$proton_dir"/proton run Minecraft.Windows.exe
